### ISSUE TITLE
This script uses unnecessary or undocumented RuneLite settings

### ISSUE THREAD

**Issue by 1player** [TormStorm/jagex-launcher-linux#102]
The runelite spawning script sets some unnecessary environment variables for no discernible reason, i.e.: 

```
--env=PULSE_LATENCY_MSEC=200 \
--env='vblank_mode=0' \
--env='MESA_GL_VERSION_OVERRIDE=4.5FC'
```

These seem to be necessary only for the RS3 binary, as [only the RS3 wiki mentions these settings](https://runescape.wiki/w/Linux#Environment_variables). They have no reason in being set in Runelite, which is a completely different application. Also, forcibly disabling vsync (I want to play with vsync enabled) or messing with the Mesa version is not a good idea in general unless it fixes known issues.

**Comment by Calmata** [comment]
The pulse latency setting has been used to address crackling audio in both RS3 and OSRS - it has little to no discernible effect on those that don't experience this issue.

We opted to disable vsync by default across the board because some configurations soft-lock framerate in a way that cannot be circumvented with RuneLite's own plugins otherwise - however, even with vsync disabled, you are able to cap your framerate using these same plugins.

The mesa version isn't altered, that variable tells the mesa system to report an OpenGL version of 4.5 with a forwards-compatible profile. Features from OpenGL 4.5+ are only actually enabled if they are available to the GPU - otherwise it functionally does nothing. This is because some configurations will default to a version 3 feature set unless instructed otherwise, which can result in some plugins such as 117HD not functioning correctly, or at all, on these configurations.

You are, of course, free to modify your launch script as you see fit.

**Comment by TormStorm** [comment]
This has been changed with #100
