### ISSUE TITLE
Is there a way to make it run the snap version?

### ISSUE THREAD

**Issue by joeamansfield** [TormStorm/jagex-launcher-linux#107]
I noticed that opening the screenshot folder works in the snap version of runelite, but not the flatpak version that was installed with lutris, and I'm wondering if there is a simple way to make the jagex launcher open the snap version and still pass all the access tokens and such.

**Comment by yeyande** [comment]
When I installed this version, it was trying to use my native java. I went into `$GAMEDIR/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite` and edited `runelite.sh` to a `flatpak run net.runelite.RuneLite` instead of the java command. You should be able to do the same thing with snap! I'm not entirely sure what the syntax is for snap, but it [looks like](https://askubuntu.com/questions/759557/how-to-start-a-snap-package) it might be something like `snap run runelite`?

**Comment by nmlynch94** [comment]
+1 to the above. That will be your best bet. However, the snap version tends to be out of date in my experience. Do you get an error I the logs or anything when you try to open that folder? Do the screenshots save, but the folder just won’t open? I will test it at some point.

**Comment by joeamansfield** [comment]
When I tried to open the folder by clicking the button, nothing seemed to
happen, but I don't know what logs I should be checking. Also not sure
where exactly the screenshot folder is, so I don't know if screenshots are
saving.

**Comment by nmlynch94** [comment]
What OS and Desktop Environment are you using?

**Comment by joeamansfield** [comment]
I'm using Ubuntu 22.04 LTS and I haven't changed it so it should be GNOME I
believe.

**Comment by nmlynch94** [comment]
If you run `xdg-open https://google.com` does it open a browser?

**Comment by joeamansfield** [comment]
Yeah, that opened google up in firefox.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
