### ISSUE TITLE
Jagex Launcher Not Starting After Installation

### ISSUE THREAD

**Issue by nxckolai** [TormStorm/jagex-launcher-linux#60]
Hello, I am having some trouble installing the Jagex Launcher on my Steam Deck. I have followed the installation guide and installed the Jagex Launcher through Lutris, however the launcher won't boot up. I've tried starting it through Steam after adding it through boilr as well launching directly through Lutris. Both result in either Steam or Lutris saying "Running..." followed by the Play button returning to normal. Any advice would be appreciated, thank you.

**Comment by MushyMarks** [comment]
Use an older copy of the yml script, the latest version seems be bored, I've tried it on multiple machines and 90% of the time it straight up is broken and if it runs it does so poorly however using older download scripts works fine across the board.  Gl my friend

**Comment by nxckolai** [comment]
I tried using an older download script and I was still experiencing issues. I’ve redownloaded and installed and I’ve come to realize that I am experiencing the same issue as user @gxtav, error code  1280. In another issue thread they mentioned testing regressions with the latest releases of lutris-ge-proton. Gonna try to figure out how to download lutris ge proton 8-10 since it seems to be the last working version.

**Comment by MushyMarks** [comment]
Ahh glad to hear you've worked it out, you can download pretty much any wine version using ProtomUp-Qt.

**Comment by nmlynch94** [comment]
@nxckolai To clarify, does it launch in Desktop mode and just not in Game Mode in steam? Or neither? 

We used to hard-code the version of proton-wine-GE to use, but Lutris has been iterating on the versions of supported proton much more quickly now. This resulted in the script being broken every week or two due to that version being out of date. 

Lutris docs say removing that version will make the installer default to the latest version of proton-ge, but we are finding that is not the case and it is kind of unpredictable. Thinking that may be the cause of these types of issues. We are working on a fix to hopefully solve both of those problems.

Can you try adding this line https://github.com/TormStorm/jagex-launcher-linux/commit/7eab8ee6ef02434979031e4b5e5dc9238140f868 into your script, but change the 12 to a 13 (the latest proton-GE version at the time of writing) and see if that works? If not, I'll send instructions on how to give logs so I can dig deeper. 

I tested a fresh install on my steam deck and it worked which is why I suspect Lutris selecting the wrong version of wine for you.

**Comment by nxckolai** [comment]
@nmlynch94 the Jagex Launcher doesn't launch in either desktop mode or game mode. I've tried launching it through Lutris and Steam after adding it through boilr and still no change. I will try a fresh install right now with the script change you suggested and see what happens. In case this helps, interestingly I have been able to get the Jagex Launcher to work in desktop mode if I add the JagexLauncher.exe to Steam and run it using ge-proton8-11. However, the launcher doesn't recognize Runelite as being installed. I read issue thread #43 and verified that my Registry entry was correct so I'm not sure why it wasn't recognizing Runelite.

**Comment by nxckolai** [comment]
I just did a fresh install and added line 22 into the jagexlauncher.yml yet still no change. After clicking play the button turns to say launching, stop, and right back to play again. Here is the log file from Lutris. Thanks again for any assistance.

> Started initial process 964 from /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine /home/deck/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
dlopen C:\Program Files (x86)\Jagex Launcher\libcef.dll: 
Monitored process exited.
Initial process has exited (return code: 1280)
Exit with return code 1280

**Comment by nmlynch94** [comment]
@nxckolai When you say you checked the registry value, do you mean you checked in Lutris? Running it via steam would mean steam creates it's own proton prefix, and then you would almost certainly need to add the registry entry manually to that. 

If that's the case, you can achieve this by going to the steam deck store and installing "protontricks". Run that from the app menu -> choose your game -> Default Prefix -> edit registry. Here, you can add the registry entry referenced in #43.

As for it running in steam but not in Lutris...I'm not sure why that would be the case. I can't reproduce it on my steam deck unfortunately. The good news is, if this steam workaround works, it might be something we can use to help the other error 1280s in the meantime while we try to figure out what is going on.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
